##############################################################################
# Copyright (c) 2015 by Patrick Hall, jpatrickhall@gmail.com                 #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License");            #
# you may not use this file except in compliance with the License.           #
# You may obtain a copy of the License at                                    #
#                                                                            #
#   http://www.apache.org/licenses/LICENSE-2.0                               #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
##############################################################################

### standard output ###########################################################
# two primary R core functions are used to print information to the console
#   print() and cat()
# print is a generic function that responds differently to different classes 
#   of R objects
# note that '.' is just a character, it does not denote object membership
#   as in Java and Python
# cat() simply attempts to prints string literals
# an object with no functions or operators is also printed to the console

x <- 'Hello World!'
print(x)
cat(x)
x

class(x) <- 'some.class'
print(x)
cat(x) 
x

### import libraries ##########################################################

# R contains thousands of packages for many different purposes
# Packages are:
#   - nearly always free and open source
#   - installed using the install.packages() function or a GUI command
#   - of varying quality
#   - loaded using the library() function, after being installed

library(dplyr)    # popular package for data wrangling with consistent syntax
library(ggplot2)  # popular package for plotting with consistent syntax

# surpress warnings about versions and object masking
# using suppressPackageStartupMessages()
# suppressPackageStartupMessages(library(dplyr))
# suppressPackageStartupMessages(library(ggplot2))

### working directory #########################################################

# enter the directory location of this file within single quotes
# '<-' is the preferred assignment operator in R
# '/' is the safest directory separator character to use

git_dir <- 'C:/workspace/GWU_data_mining/week_2'

# set the working directory
# the working directory is where files are written to and read from by default
# setwd() sets the working directory
# getwd() prints the current working directory
setwd(git_dir)
getwd()

### generate a sample data set ################################################

# set the number of rows and columns for the sample data set
n_rows <- 1000
n_vars <- 5

# create a key variable
# a key variable has a unique value for each row of a data set
# seq() generates values from a number (default = 1), to another number, by
#   a certain value (default = 1)
# many types of data structures in R have key variables (a.k.a. row names) by
#   default
key <- seq(n_rows)

# create lists of strings that will become column names
# paste() concatentates strings with a separator character in between them
num_vars <- paste('numeric', seq_len(n_vars), sep = '')
char_vars <- paste('char', seq_len(n_vars), sep = '')

# initialize a data.frame with the key variable
scratch_df <- data.frame(INDEX = key)

# add n_var numeric columns, each with n_row rows, to the data.frame
# each column contains random uniform numeric values generated by runif()
# replicate() replicates n_row length lists of numeric values n_vars times
scratch_df[, num_vars] <- replicate(n_vars, runif(n_rows))

# sapply() applies a function to a sequence of values
# LETTERS is a character vector containing uppercase letters
# an anonymous function is defined that replicates a value 8 times with no
#   seperator character
# replicate() replicates n_var lists of n_row elements from text_draw sampled
#   randomly from test_draw using the sample() function
text_draw <- sapply(LETTERS[1:7],
                    FUN = function(x) paste(rep(x, 8), collapse = ""))
scratch_df[, char_vars] <- replicate(n_vars,
                                     sample(text_draw, n_rows, replace = TRUE))

# convert from standard data.frame to dlpyr table
# R has many data types: http://www.statmethods.net/input/datatypes.html
scratch_tbl <- tbl_df(scratch_df)

# use the dplyr::glimpse function to see a summary of the generated data set
glimpse(scratch_tbl)

### plotting variables in the table ###########################################
# ggplot allows you to overlay graphics using the '+' operator
# plot univariate densities of numeric1 and char1 using the geom_bar()
#   components
# gtitle adds title
# coord_flip rotates the bar chart

ggplot(scratch_tbl, aes(numeric1)) +
  geom_bar(stat = "bin", fill = "blue", bins = 100) +
  ggtitle('Histogram of Numeric1')

ggplot(scratch_tbl, aes(char1)) +
  geom_bar(aes(fill=char1)) +
  ggtitle('Histogram of Char1') +
  coord_flip()

### subsetting the table ######################################################

# subset variables using dplyr::select
# subset a range of variables with similar names and numeric suffixes
# subset all the variables whose names begin with 'char'
# subset variables by their names
num_vars <- select(scratch_tbl, num_range('numeric', 1:n_vars))
char_vars <- select(scratch_tbl, starts_with('char'))
mixed_vars <- select(scratch_tbl, one_of('numeric1', 'char1'))

# subset rows using multiple dplyr functions
# subset rows using their numeric indices
# subset top rows based on the value of a certain variable
# subset rows where a certain variable has a certain value
some_rows <- slice(scratch_tbl, 1:10)
sorted_top_rows <- top_n(scratch_tbl, 10, numeric1)
AAAAAAAA_rows <- filter(scratch_tbl, char1 == 'AAAAAAAA')

### sorting the table #########################################################
# sort tables using dplyr::arrange
# sort by one variable
# sort by two variables

sorted <- arrange(char_vars, char1)
sorted2 <- arrange(char_vars, char1, char2)

### adding data to the table ##################################################
# add data to a table using dplyr:: bind and dplyr::join
# bind smashes tables together
# join combines tables based on matching values of a shared variable

bindr <- bind_rows(sorted, sorted2)
bindc <- bind_cols(sorted, sorted2)

sorted_left <- arrange(select(scratch_tbl, one_of('INDEX', 'char1')), char1)
right <- select(scratch_tbl, one_of('INDEX', 'numeric1'))
joined <- left_join(sorted_left, right, by = 'INDEX')

### comparing tables ##########################################################
# comparing tables using dplyr::all.equal
# dplyr::all.equal will test tables for equality despite the order of rows
#   and/or columns
# very useful for keeping track of changes to important tables

test <- select(scratch_tbl, one_of('INDEX', 'numeric1', 'char1'))
print(all.equal(joined, test, ignore_row_order = FALSE))
print(all.equal(joined, test, ignore_col_order = FALSE))
print(all.equal(joined, test))

### summarizing tables ########################################################
# combine rows of tables into summary values with dplyr::summarise and
#   dplyr::summarise_each
# summarize one variable using summarise, avg is the name of the created var
# summarize many variables using summarise_each, fun() defines the summary
#   function

ave <- summarise(num_vars, avg = mean(numeric1))
all_aves <-summarise_each(num_vars, funs(mean))

### by-group processing #######################################################
# dplyr::group_by groups a data set together based on the values of a certain
#   variable
# operations can then be applied to groups
grouped <- group_by(joined, char1)
grouped <- summarise(grouped, avg = mean(numeric1))

### exporting and importing the table #########################################
# the R core function write.table enables reading and writing of text files.

# export
filename <- paste(git_dir, 'scratch.csv', sep = '/')
write.table(scratch_tbl, file = filename, quote = FALSE, sep = ',',
            row.names = FALSE)

# import
import <- read.table(filename, header = TRUE, sep = ',')