ec2_data_dict = {
   "t2.nano":{
      "cores":"1",
      "memory":"0.5"
   },
   "t2.micro":{
      "cores":"1",
      "memory":"1"
   },
   "t2.small":{
      "cores":"1",
      "memory":"2"
   },
   "t2.medium":{
      "cores":"2",
      "memory":"4"
   },
   "t2.large":{
      "cores":"2",
      "memory":"8"
   },
   "t2.xlarge":{
      "cores":"4",
      "memory":"16"
   },
   "t2.2xlarge":{
      "cores":"8",
      "memory":"32"
   },
   "m4.large":{
      "cores":"2",
      "memory":"8"
   },
   "m4.xlarge":{
      "cores":"4",
      "memory":"16"
   },
   "m4.2xlarge":{
      "cores":"8",
      "memory":"32"
   },
   "m4.4xlarge":{
      "cores":"16",
      "memory":"64"
   },
   "m4.10xlarge":{
      "cores":"40",
      "memory":"160"
   },
   "m4.16xlarge":{
      "cores":"64",
      "memory":"256"
   },
   "c4.large":{
      "cores":"2",
      "memory":"3.77"
   },
   "c4.xlarge":{
      "cores":"4",
      "memory":"7.5"
   },
   "c4.2xlarge":{
      "cores":"8",
      "memory":"15"
   },
   "c4.4xlarge":{
      "cores":"16",
      "memory":"30"
   },
   "c4.8xlarge":{
      "cores":"36",
      "memory":"60"
   },
   "p2.xlarge":{
      "cores":"4",
      "memory":"61"
   },
   "p2.8xlarge":{
      "cores":"32",
      "memory":"488"
   },
   "p2.16xlarge":{
      "cores":"64",
      "memory":"732"
   },
   "x1.16xlarge":{
      "cores":"64",
      "memory":"976"
   },
   "x1.32xlarge":{
      "cores":"128",
      "memory":"1952"
   },
   "r3.large":{
      "cores":"2",
      "memory":"15"
   },
   "r3.xlarge":{
      "cores":"4",
      "memory":"30.5"
   },
   "r3.2xlarge":{
      "cores":"8",
      "memory":"61"
   },
   "r3.4xlarge":{
      "cores":"16",
      "memory":"122"
   },
   "r3.8xlarge":{
      "cores":"32",
      "memory":"244"
   },
   "r4.large":{
      "cores":"2",
      "memory":"15.25"
   },
   "r4.xlarge":{
      "cores":"4",
      "memory":"30.5"
   },
   "r4.2xlarge":{
      "cores":"8",
      "memory":"61"
   },
   "r4.4xlarge":{
      "cores":"16",
      "memory":"122"
   },
   "r4.8xlarge":{
      "cores":"32",
      "memory":"244"
   },
   "r4.16xlarge":{
      "cores":"64",
      "memory":"488"
   },
   "i3.large":{
      "cores":"2",
      "memory":"7"
   },
   "i3.xlarge":{
      "cores":"4",
      "memory":"30.5"
   },
   "i3.2xlarge":{
      "cores":"8",
      "memory":"61"
   },
   "i3.4xlarge":{
      "cores":"16",
      "memory":"122"
   },
   "i3.8xlarge":{
      "cores":"32",
      "memory":"244"
   },
   "i3.16xlarge":{
      "cores":"64",
      "memory":"488"
   },
   "d2.xlarge":{
      "cores":"4",
      "memory":"30.5"
   },
   "d2.16xlarge":{
      "cores":"8",
      "memory":"61"
   },
   "d2.16xlarge":{
      "cores":"16",
      "memory":"122"
   },
   "d2.16xlarge":{
      "cores":"36",
      "memory":"244"
   },
}
